language: node_js

node_js:
  - "9"

sudo: false
dist: trusty

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script: 
  - ng lint
  - ng test --watch false -cc
  - ng build
#  - npm run e2e
