language: node_js

node_js:
  - "9"

sudo: required
dist: trusty

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - npm install -g ganache-cli truffle

script:
  - ganache-cli 2> /dev/null 1> /dev/null &
  - sleep 5
  - ganache-cli -p 7545
  - truffle migrate --reset
  - truffle test
  - ng lint
  - ng test --single-run
  - ng build
#  - npm run e2e
