language: node_js

node_js:
  - "9"

sudo: required
dist: trusty

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - ng lint
  - ng test
  - ng build
#  - npm run e2e
