sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "9"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
   - google-chrome-stable --headless --no-sandbox

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g ganache-cli truffle

script:
  - ganache-cli 1> /dev/null &
  - sleep 5
  - truffle compile
  - truffle migrate
  - truffle test
  - ng lint
  - ng test --watch false
  - npm run e2e
  - ng build --base-href --prod
